

CREATE TABLE AUTH.Users (
  USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(45) NOT NULL,
  FIRSTNAME VARCHAR(45) NOT NULL,
  LASTNAME VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL,
  ENABLED TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`USER_ID`)
  );


CREATE TABLE AUTH.User_Roles (
  USER_ROLE_ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT UNSIGNED NOT NULL,
  ROLE varchar(45) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID),
  UNIQUE KEY UNIQ_USER_ID_ROLE (ROLE, USER_ID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)
  );

CREATE INDEX USER_ID_IX ON AUTH.User_Roles (USER_ID);

create table AUTH.oauth_client_details (
  client_id VARCHAR(256) PRIMARY KEY,
  resource_ids VARCHAR(256),
  client_secret VARCHAR(256),
  scope VARCHAR(256),
  authorized_grant_types VARCHAR(256),
  web_server_redirect_uri VARCHAR(256),
  authorities VARCHAR(256),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additional_information VARCHAR(4096),
  autoapprove VARCHAR(256)
);

