


CREATE TABLE USER.Users (
  USER_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(60) NOT NULL,
  ENABLED TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`USER_ID`)
  );


CREATE TABLE USER.User_Roles (
  USER_ROLE_ID int(11) NOT NULL AUTO_INCREMENT,
  USER_ID INT UNSIGNED NOT NULL,
  ROLE varchar(45) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID),
  UNIQUE KEY UNIQ_USER_ID_ROLE (ROLE, USER_ID),
  KEY USER_ID_IX (USER_ID),
  CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES users (USER_ID)
  );



INSERT INTO users(username,password,enabled) VALUES ( 'marku','$2a$04$pc0IBab7wgA81Zn/xxElXOa/wjqAXklWFP9a4G6O57QzWQVhIdfKS', true);
INSERT INTO users(username,password,enabled) VALUES ('mmurun','$2a$04$ATW2Gkpurt.07828Q12WNuy90tpH22yutdrErbv2wKGGws4zVetRK', true);


INSERT INTO user_roles (USER_ID, role) VALUES (1, 'ROLE_USER');
INSERT INTO user_roles (USER_ID, role) VALUES (1, 'ROLE_ADMIN');
INSERT INTO user_roles (USER_ID, role) VALUES (2, 'ROLE_USER');